default: &default
  adapter: postgresql
  database: daily_hub_development
  username: postgres
  password:
  host: localhost
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: daily_hub_test